ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN isScatter CHAR(1);

ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN title VARCHAR(50);

ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN xlabel VARCHAR(50);

ALTER TABLE APP.REPORTINSTANCEPOINTS
ADD COLUMN ylabel VARCHAR(50)